networks:
  network_main:

x-common-service: &common-service
  image: trading_companion:${VERSION}
  depends_on:
    - postgres
  env_file:
    .env
  networks:
    - network_main

services:
  api:
    <<: *common-service
    container_name: api
    command: sh -c "PYTHONPATH=src uvicorn src.api:app --host 0.0.0.0 --port 8080"
    ports:
      - '8080:8080'
  dagster:
    <<: *common-service
    container_name: dagster
    command: sh -c "DAGSTER_HOME=/app PYTHONPATH=/app dagster dev -h \"0.0.0.0\" -p 3000 -w dagster_workspace.yaml"
    ports:
      - '3000:3000'
  postgres:
    image: postgres:17.2
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ADMIN}
      - POSTGRES_USER=${POSTGRES_USER_ADMIN}
    networks:
      - network_main
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
