version: '3.8'

services:
  api:
    command: sh -c "PYTHONPATH=src uvicorn src.api:app --host 0.0.0.0 --port 8080 --reload --reload-dir ./src --reload-exclude '__pycache__/*'"
    stdin_open: true
    tty: true
    volumes:
      - ./bin:/app
  dagster:
    stdin_open: true
    tty: true
    volumes:
      - ./bin:/app
  ui:
    image: trading_companion_ui:${VERSION}
    container_name: ui
    depends_on:
      - api
    env_file:
      .env
    networks:
      - network_main
    ports:
      - '9000:9000'
    command: sh -c "npm start"
    stdin_open: true
    tty: true
    volumes:
      - ./web/index.html:/app/web/index.html
      - ./web/src:/app/web/src
      - ./web/package.json:/app/web/package.json
      - ./web/tsconfig.json:/app/web/tsconfig.json
      - ./web/vite.config.ts:/app/web/vite.config.ts
