version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data
  scripts:
    image: scripts:1.0.0
    container_name: scripts
    depends_on:
      - postgres
    env_file:
      .env
    stdin_open: true
    tty: true
    volumes:
      - ./bin:/app
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    env_file:
      - .env
    environment:
      SPLUNK_ADD: "monitor /app/logs"
      SPLUNK_START_ARGS: "--accept-license"
    ports:
      - '8000:8000'
      - '8089:8089'
    volumes:
      - ./bin/logs:/app/logs
      - splunk-conf:/opt/splunk/etc
      - splunk-data:/opt/splunk/var
volumes:
  postgres-data:
  splunk-conf:
  splunk-data:
