version: '3.8'

services:
  api:
    stdin_open: true
    tty: true
    volumes:
      - ./bin:/app
  dagster:
    stdin_open: true
    tty: true
    volumes:
      - ./bin:/app
  web:
    image: trading_companion_web:${VERSION}
    container_name: web
    depends_on:
      - api
    env_file:
      .env
    networks:
      - network_main
    ports:
      - '9000:9000'
    command: sh -c "npm start"
    stdin_open: true
    tty: true
    volumes:
      - ./web/src:/app/web/src
